cr/urls.py
from django.contrib import admin
from django.urls import path, re_path

from carental import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name="home"),

    path('reserve', views.reserve, name="reserve"),
    path('admin/reservations', views.reservations, name="reservations"),
    path('possibe_reservation', views.possibe_reservation, name="possibe_reservation"),

    path('admin/add_car/', views.add_car, name="add_car"),
    path('admin/update_car/', views.update_car, name="update_car"),

    path('cars/', views.cars, name="cars"),

    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='carental/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='carental/logout.html'), name='logout'),

    path('promotion/', views.promotion, name='promotion'),
    path('penalize/', views.penalize, name='penalize'),
    path('penalties/', views.penalties, name='penalties'),
    path('cancellations/', views.cancellations, name='cancellations'),
    path('add_balance/', views.add_balance, name='add_balance'),

    path('admin/', admin.site.urls),
]

carental/models.py
import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models


FUEL_CHOICES =(
    ("1", "Diesel"),
    ("2", "Essence"),
)


class Car(models.Model):
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    fuel = models.CharField(max_length=100, choices=FUEL_CHOICES, null=True, default='2')
    mileage = models.PositiveIntegerField()
    price = models.PositiveIntegerField()
    image = models.ImageField(upload_to='carental/static/carental/car_images')
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.brand + ' ' + self.model


class User(AbstractUser):
    balance = models.PositiveIntegerField(default=0, blank=True)
    penalty = models.BooleanField(default=False)

    def __str__(self):
        return self.username


class Reservation(models.Model):
    car = models.ForeignKey('Car', on_delete=models.CASCADE)
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    date = models.DateTimeField()
    finish_date = models.DateTimeField()
    duration = models.PositiveSmallIntegerField(default=1)
    cancelled = models.CharField(choices=(('false', 'false'), ('true', 'true'), ('seen', 'seen')), default='false', max_length=10)

    def __str__(self):
        return str(self.car) + ' by: ' + str(self.user) + ' at: ' + self.date.strftime('%Y/%m/%d %H:00')


class Promotion(models.Model):
    car = models.OneToOneField('Car', on_delete=models.CASCADE)
    percentage = models.PositiveSmallIntegerField(choices=[(x, x) for x in range(5, 101, 5)])
    begin_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return f"{self.car.model}: {self.percentage}% - {self.begin_date} to {self.end_date}"

carental/forms.py
import datetime

from carental.models import Car, Reservation
from django.forms import ModelForm, NumberInput
from django import forms
from carental.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'balance']


class CarForm(ModelForm):
    class Meta:
        model = Car
        fields = '__all__'


# class DateInput(forms.DateInput):
#     input_type = 'date'
#
#
# class ReservationForm(ModelForm):
#     class Meta:
#         model = Reservation
#         fields = ['date', 'duration']
#         widgets = {
#             'date': DateInput(attrs={'value': datetime.date.today}),
#             'duration': NumberInput(attrs={'min': '12', 'max': '720', 'step': '12'})
#         }

carental/views.py
import datetime
import pytz
from collections import namedtuple

from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.db.models import F
from django.urls import reverse

from .forms import CarForm
from .models import Car, Reservation, User, Promotion
from .forms import UserRegisterForm

utc = pytz.UTC


@login_required
def profile(request):
    return render(request, 'carental/profile.html')


def home(request):
    return render(request, 'carental/index.html')


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            form.save()
            messages.success(request, f'Account created for {username}!')
            return redirect('home')
    else:
        form = UserRegisterForm()
    return render(request, 'carental/register.html', {'form': form})


@permission_required('user.is_superuser')
def add_car(request):
    if request.method == "POST":
        form = CarForm(request.POST)
        if form.is_valid():
            form.save()
    return render(request, "carental/add_car.html", {'carForm': CarForm()})


# TODO add a form for customized search
def cars(request):
    return render(request, "carental/cars.html", {'cars': Car.objects.all()})


@permission_required('user.is_superuser')
def update_car(request):
    if request.method == "POST":
        form = request.POST
        updatedCar = Car.objects.filter(pk=form.get('id'))
        updatedCar.update(mileage=form.get('mileage'), price=form.get('price'),
                          available=True if form.get('available') else False)
    return render(request, "carental/update_car.html", {'cars': Car.objects.all()})


@permission_required('user.is_superuser')
def reservations(request):
    prettyReservation = namedtuple('Reservation', ['id', 'car', 'user', 'date', 'finish_date', 'duration'])
    prettyReservations = []
    reservations = Reservation.objects.all()
    for reservation in reservations:
        prettyReservations.append(prettyReservation(reservation.id,
                                                    ' '.join(Car.objects.values('brand', 'model').get(
                                                        pk=reservation.car_id).values()),
                                                    ' '.join(User.objects.values('first_name', 'last_name').get(
                                                        pk=reservation.user_id).values()),
                                                    reservation.date.strftime('%Y/%m/%d %H:00'),
                                                    reservation.finish_date.strftime('%Y/%m/%d %H:00'),
                                                    reservation.duration // 24
                                                    ))

    return render(request, "carental/reservations.html", {'reservations': prettyReservations})


@login_required
def reserve(request):
    if request.method == "POST":
        form = request.POST
        print(f"\nthe form: {form}")
        if form.get('duration'):  # request comes from the reserve page
            if request.user.balance < (int(form['duration'])) * int(form['price']):
                return JsonResponse({"tag": "danger", "message": """Unsufficient funds, You can recharge your account from 
                <a data-toggle="modal" data-target="#exampleModal">here</a>"""
                                     })
            if not possibe_reservation(request):
                return JsonResponse({"tag": "danger", "message": "Reservation not possible at the selected time"})
            date = form['date'] + ' ' + form['time']
            date = datetime.datetime.strptime(date, '%Y-%m-%d %H')
            duration = int(form['duration']) * 24
            try:
                Reservation(car_id=form['car_id'], user_id=request.user.id, date=date,
                            finish_date=date + datetime.timedelta(hours=duration), duration=duration).save()
                u = User.objects.get(pk=request.user.id)
                u.balance -= int(form['duration']) * int(form['price'])
                u.save()
                return JsonResponse({"tag": "success", "message": "Reservation saved", "balance": u.balance})
            except:
                return JsonResponse({"tag": "danger", "message": "Reservation failed"})
        else:  # request comes from the cars page
            car = ' '.join(Car.objects.values('brand', 'model').get(pk=form.get('id')).values())
            return render(request, "carental/reserve.html",
                          {'car': {'id': form.get('id'), 'name': car, 'price': form.get('price')},
                           'duration_list': [x for x in range(2, 31)],
                           'time_list': [f'{x}' for x in range(8, 24)]})
    return cars(request)


# Check if the requested reservation overlaps with a previous one
@login_required
def possibe_reservation(request):
    if request.method == "POST":
        form = request.POST
        form_date = form['date'] + ' ' + form['time']
        form_date = datetime.datetime.strptime(form_date, '%Y-%m-%d %H')
        same_car_reservations = list(Reservation.objects.filter(car_id=form['car_id']))
        for car_res in same_car_reservations:
            car_res_date = car_res.date.replace(tzinfo=utc)
            form_date = form_date.replace(tzinfo=utc)
            print(f"res date: {car_res_date}")
            print(f"form date: {form_date}")
            if car_res_date <= form_date < car_res_date + datetime.timedelta(hours=car_res.duration) or \
                    form_date <= car_res_date < form_date + datetime.timedelta(hours=int(form['duration']) * 24):
                print("nope")
                return False
        return True


# tell the user if a car is on a sale
def promotion(request):
    promotions = list(Promotion.objects.all())
    if len(promotions) == 0:
        return JsonResponse({"tag": "danger", "message": "no promotions"})
    else:
        for i in range(1, len(promotions)):
            if promotions[-i].begin_date <= datetime.date.today() <= promotions[-i].end_date:
                return JsonResponse({"tag": "success", "percentage": promotions[-i].percentage,
                                     "car": promotions[-i].car.brand + " " + promotions[-i].car.model,
                                     "end": promotions[-i].end_date})


# penalize the user if he made a reservation and didn't commit
@permission_required('user.is_superuser')
def penalize(request):
    if request.method == "POST":
        form = request.POST
        r = Reservation.objects.get(pk=form['id'])
        if form['action'] == 'penalize':
            u = User.objects.get(pk=r.user_id)
            u.penalty = True
            if u.balance > 999:
                u.balance -= 1000
            else:
                u.balance = 0
            u.save()
            print(f"user id: {r.user_id}, penalty: {User.objects.get(pk=r.user_id).penalty}")
            r.delete()
            messages.success(request, f'user: ({u.username}) penalized and reservation: ({r}) deleted!')
        elif form['action'] == 'cancel':
            r.cancelled = 'true'
            r.save()
            messages.success(request, f'Reservation ({str(r)}) Cancelled')
        return redirect('reservations')


# tell the user if he was penalized
@login_required
def penalties(request):
    u = User.objects.get(pk=request.user.pk)
    print(str(u) + str(u.penalty))
    if u.penalty:
        u.penalty = False
        u.save()
        return JsonResponse({"tag": "danger",
                             "message": '<span style="font-size: 20px; color: red">1000 DA </span> have been deducted from your account for not honoring your engagement'})
    else:
        return JsonResponse({"tag": "success"})


# tell the user if one of his reservations were cancelled
@login_required
def cancellations(request):
    u = User.objects.get(pk=request.user.pk)
    r = list(Reservation.objects.filter(user_id=u.id, cancelled='true'))
    if len(r) > 0:
        r[-1].cancelled = 'seen'
        r[-1].save()
        return JsonResponse({"tag": "danger", "message": f"your {r[-1]} reservation was cancelled, "
        f"would you like to <a href=\"{reverse('reserve')}\">make another reservation?</a>"})
    return JsonResponse({"tag": "success", "message": f'so far so good'})


# TODO: smooth redirects
@login_required
def add_balance(request):
    if request.method == "POST":
        try:
            form = request.POST
            print(form)
            User.objects.filter(pk=form['user']).update(balance=F('balance') + form['amount'])
            print(f"User: {form['user']}, new amount: {User.objects.get(pk=form['user']).balance}")
            s = '../' + str(request.META.get('HTTP_REFERER', '')).split('/', 3)[-1]     # to redirect the user to the current page
            return redirect(s)
        except:
            return None
    else:
        return redirect('cars')

carental/templates/carental/add_car.html
{% extends 'carental/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Add cars
{% endblock %}

{% block body %}
    <div class="container">
        <main role="main" class="container d-flex justify-content-center">
            <div class="row">
                <div class="col-md-12">
                    <form action="{% url 'add_car' %}" method="POST">
                        {% csrf_token %}
                        {{ carForm|crispy }}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </main>
    </div>

{% endblock %}

carental/templates/carental/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'carental/css/' %}minty_bootstrap.css">

    <script src="{% static 'carental/js/' %}jquery-3.4.1.js"></script>

    {% block extra_dependencies %}
    {% endblock %}
    {% block style %}
    <style>
        table {
            table-layout: fixed;
        }

        table th, table td {
            overflow: hidden;
        }

        input[type=number]::-webkit-inner-spin-button,
        input[type=number]::-webkit-outer-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }

        input[type=number] {
            -moz-appearance: textfield;
        }
    </style>
    {% endblock %}
</head>
<body style="margin-top: 150px">

{% include 'carental/nav.html' %}

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add balance to your account</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'add_balance' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="hidden" name="user" value="{{ request.user.id }}">
                        <label for="amount" class="col-form-label">Amount:</label>
                        <input type="number" min="1000" class="form-control" id="amount" name="amount">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Confirm</button>
            </div>
        </div>
    </div>
</div>

{% block promotion %}
<main role="main" class="container d-flex justify-content-center">
    <div class="row">
        <div class="col-md-12">

            <div id="notification"></div>

            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}

        </div>
    </div>
</main>


<script src="{% static 'carental/js/' %}promotions.js"></script>
<script src="{% static 'carental/js/' %}penalties.js"></script>
<script src="{% static 'carental/js/' %}cancelRes.js"></script>
{% endblock %}
{% block body %}
{% endblock %}

<!--<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"-->
<!--        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"-->
<!--        crossorigin="anonymous"></script>-->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

</body>
</html>

carental/templates/carental/cars.html
{% extends 'carental/base.html' %}
{% load templatetags staticfiles %}

{% block title %}
    Cars
{% endblock %}

{%  block promotion %}{% endblock %}

{% block body %}
    <table id="carTable" class="table table-striped">
        <thead class="thead-dark">
        <tr>
            {#            <th scope="col">Id</th>#}
            <th scope="col">Brand</th>
            <th scope="col">Model</th>
            <th scope="col">Color</th>
            <th scope="col">Fuel</th>
            <th scope="col">Mileage (Km)
                {#                    <input type="hidden" name="mileage"#}
                {#                           value="{% if sorted_list %}{{ sort_list.0|reverse_sort_order }}{% else %}-mileage{% endif %}">#}
                {#                    <button type="submit">Mileage</button>#}
            </th>
            <th scope="col">Price (DA)
                {#                    <input type="hidden" name="price"#}
                {#                           value="{% if sorted_list %}{{ sort_list.1|reverse_sort_order }}{% else %}-price{% endif %}">#}
                {#                    <button type="submit">Price</button>#}
            </th>
            <th scope="col">Available
                {#                    <input type="hidden" name="available"#}
                {#                           value="{% if sorted_list %}{{ sort_list.2|reverse_sort_order }}{% else %}-available{% endif %}">#}
                {#                    <button type="submit">Available</button>#}
            </th>
            <th scope="col" style="text-align: center">Image</th>
            <th scope="col" style="text-align: center">Action</th>
        </tr>
        </thead>
        <tbody>
        {% for car in cars %}
            <form method="post" action="{% url 'reserve' %}">
                {% csrf_token %}
                <tr>
                    <input type="hidden" name="id" value="{{ car.id }}">
                    {% with car|get_promotion as promotion %}
                        <input type="hidden" name="price"
                                {% if promotion.exists %}
                               value="{{ promotion.new_price }}"
                                {% else %}
                               value="{{ car.price }}"
                                {% endif %}
                        >
                        {#                    <th scope="row">{{ car.id }}</th>#}
                        <td>{{ car.brand }}</td>
                        <td>{{ car.model }}</td>
                        <td>{{ car.color }}</td>
                        <td>{{ car.fuel|fuel_number2str }}</td>
                        <td>{{ car.mileage }} </td>
                        <td>
                            {% if promotion.exists %}
                                <span style="font-size: 25px; color: red">{{ promotion.new_price }} DA</span>
                                <br/>
                                <del>
                                    {{ car.price }}
                                </del>
                                <span style="font-size: 13px; color: limegreen">(-{{ promotion.percentage }}%)</span>
                                <br/>
                                (Until: {{ promotion.end }})
                            {% else %}
                                {{ car.price }} DA
                            {% endif %}
                        </td>
                        <td>{{ car|is_available }}</td>
                    {% endwith %}

                    <td>
                        <img src="{% static 'carental/car_images/' %}{{ car.image|img_file }}" alt=""
                             class="img-thumbnail">
                    </td>
                    <td style="text-align: center">
{#                        {% if car|is_available == 'disponible' %}#}
                            <button type="submit" class="btn btn-info">Reserve</button>
{#                        {% endif %}#}
                    </td>
                </tr>
            </form>
        {% endfor %}

        </tbody>
    </table>
    {#    </form>#}

{% endblock %}

carental/templates/carental/index.html
{% extends "carental/base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block style %}
<style>
    body {
        background: url("{% static 'carental/images/' %}home-image.jpg") no-repeat center center fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
    }

</style>
{% endblock %}

{% block body %}

<!--<div class="container-fuiled page">-->
<!--    <div class="container-fuiled">-->
<!--        <div class="row">-->
            <!--            <div class="col-md-3" ></div>-->
            <!--            <div class="col-md-6" style="margin-bottom: 100px">-->
            <!--                <a href="{% url 'cars' %}" id="to-cars">-->
            <!--                    <h1 class="text-md-center">Check our available cars!</h1>-->
            <!--                </a>-->
            <!--            </div>-->
            <!--            <div class="col-md-3" ></div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->

{% endblock body %}

carental/templates/carental/login.html
{% extends "carental/base.html" %}
{% load crispy_forms_tags %}

{% block body %}
    <div role="main" class="container d-flex justify-content-center">
        <div class="row align-middle">
            <div class="col-md-12">
                <div class="jumbotron d-flex align-items-center" style="margin-top: 100px">
                    <form method="POST">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Log In</legend>
                            {{ form|crispy }}
                        </fieldset>
                        <div class="form-group">
                            <button class="btn btn-outline-info" type="submit">Login</button>
                        </div>
                    </form>
                </div>

                <div class="border-top pt-3">
                    <small class="text-muted">
                        Need An Account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

carental/templates/carental/logout.html
{% extends "carental/base.html" %}
{% block body %}
    <main role="main" class="container d-flex justify-content-center">
        <div class="row">
            <div class="col-md-12">
                <h2>You have been logged out</h2>
                <div class="border-top pt-3">
                    <small class="text-muted">
                        <a href="{% url 'login' %}">Log In Again</a>
                    </small>
                </div>
            </div>
        </div>
    </main>
{% endblock body %}

carental/templates/carental/profile.html
{% extends "carental/base.html" %}
{% load crispy_forms_tags %}
{% block body %}
    <main role="main" class="container d-flex justify-content-center">
        <div class="row">
            <div class="col-md-12">
                <div class="content-section">
                    <div class="media">
                        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
                        <div class="media-body">
                            <h2 class="account-heading">{{ user.username }}</h2>
                            <p class="text-secondary">{{ user.email }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock body %}

carental/templates/carental/reserve.html
{% extends 'carental/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Add reservation
{% endblock %}

{% block promotion %}{% endblock %}

{% block body %}
    <div class="container">
        <main role="main" class="container d-flex justify-content-center">
            <div class="row">
                <div class="col-md-12">
                    <div id="notification"></div>
                    {#                    <div id="error"></div>#}
                    <form method="POST" id="reserve_form">
                        {% csrf_token %}

                        <input type="hidden" name="car_id" value="{{ car.id }}">
                        <input type="hidden" name="price" value="{{ car.price }}">

                        <div class="form-group">
                            <label for="id_car" class=" requiredField">Car</label>
                            <div class="input-group">
                                <input type="text" value="{{ car.name }}" class="form-control" disabled>
                            </div>
                        </div>


                        {#                        {{ reservationForm|crispy }}#}

                        <div id="div_id_date" class="form-group"><label for="id_date" class=" requiredField">
                            Date<span class="asteriskField">*</span> </label>
                            <div class=""><input type="date" name="date"
                                                 class="dateinput form-control" required id="id_date"></div>
                        </div>

                        <div id="div_id_time" class="form-group"><label for="id_time" class="requiredField">
                            Time<span class="asteriskField">*</span> </label>
                            <select name="time" class="custom-select my-1 mr-sm-2" id="id_time" required>
                                <option value="07" selected>07:00</option>
                                {% for option in time_list %}
                                    <option value="{{ option }}">{{ option }}:00</option>
                                {% endfor %}
                            </select>
                        </div>


                        <div id="div_id_duration" class="form-group"><label for="id_duration" class=" requiredField">
                            Duration<span class="asteriskField">*</span> (Days)</label>
                            <select name="duration" class="custom-select my-1 mr-sm-2" id="id_duration" required>
                                <option value="1" selected>1</option>
                                {% for option in duration_list %}
                                    <option value="{{ option }}">{{ option }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <button type="submit" id="submit-button" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </main>
    </div>

    <script>
        $(document).ready(function () {
            let today = new Date();
            let dateInput = $('#id_date');
            let timeInput = $('#id_time');
            let notification = $('#notification');
            let todayDate = [today.getFullYear(), today.getMonth() + 1, today.getDate()].join('-');

            dateInput.val(todayDate);
            timeInput.val(function () {
                if (today.getHours() < 12) return today.getHours() + 2;
                return '07'
            });

            $(document).on('change', '#id_date, #id_time', function () {
                if (new Date(dateInput.val()).getTime() < new Date(todayDate).getTime()
                    || (new Date(dateInput.val()).getTime() == new Date(todayDate).getTime()
                        && timeInput.val() <= today.getHours())) {
                    $('#submit-button').prop("disabled", true);
                    notification.html('<div style="margin-bottom: 50px;" class="alert alert-warning">Please choose a future Date</div>')
                } else {
                    $('#submit-button').prop("disabled", false);
                    notification.html("");
                }
            });

            $(document).on('click', '#submit-button', function (event) {
                event.preventDefault();
                $.ajax({
                    type: "post",
                    url: "reserve",
                    data: $('#reserve_form').serialize(),
                    success: function (msg) {
                        notification.html('<div style="margin-bottom: 50px;" class="alert alert-' + msg.tag + '">' + msg.message + '</div>');
                        if (msg.tag == "success") {
                            $('#balance').text("Balance: " + msg.balance + " DA");
                        }
                    },
                    error: function (data) {
                        console.log('An error occurred:');
                        console.log(data);
                    },
                });
            });


            $(document).on('click', '#balance-div', function (event) {
                event.preventDefault();
                console.log("heeeeeeeeeeey");
                $('#balance-div').html = '<input type="number">';
            });


        });
    </script>
{% endblock %}